# Generated by Django 4.2.4 on 2024-04-13 09:53

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additions', '0006_alter_city_country_id_alter_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='images/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('data', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес места проведения')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('gallery', models.ImageField(null=True, upload_to='images/', verbose_name='Галерея')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.city')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='images/', verbose_name='Фото спикера')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия Имя')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специлизация')),
                ('info', models.TextField(max_length=500, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='EventFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(default=events.models.get_default_fields)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.formtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_form_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_event', to='events.eventformtemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='event_speaker', to='events.speaker', verbose_name='Спикеры на эвент'),
        ),
    ]
