# Generated by Django 5.0.7 on 2024-08-01 11:17

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(null=True, upload_to='images/', verbose_name='Галерея')),
                ('caption', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('fields', models.JSONField(default=events.models.get_default_fields)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.CharField(max_length=255, null=True, verbose_name='Причина отказа')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото спикера')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия Имя')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='images/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес места проведения')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('offline', models.BooleanField(default=False, verbose_name='Офлайн')),
                ('record_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на запись')),
                ('stream', models.URLField(blank=True, null=True, verbose_name='Ссылка на стрим')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.city')),
            ],
        ),
    ]
