# Generated by Django 4.2.4 on 2024-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='images/', verbose_name='Фото спикера')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия Имя')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специлизация')),
                ('info', models.TextField(max_length=500, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('data', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('position', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('gallery', models.ImageField(upload_to='images/', verbose_name='Галерея')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('speakers', models.ManyToManyField(related_name='event_speaker', to='events.speaker', verbose_name='Спикеры на эвент')),
            ],
        ),
    ]
