# Generated by Django 5.0.7 on 2024-08-01 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Администратор ивента'),
        ),
        migrations.AddField(
            model_name='event',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.specialization', verbose_name='Специализации на эвенте'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='events_gallery', to='events.eventgallery', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_event', to='events.formtemplate'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='specializations',
            field=models.ManyToManyField(to='users.specialization'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='event_speaker', to='events.speaker', verbose_name='Спикеры на эвент'),
        ),
    ]
