# Generated by Django 4.2.4 on 2024-04-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventformtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фото спикера'),
        ),
    ]
