# Generated by Django 4.2.4 on 2024-08-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="gallery",
        ),
        migrations.AddField(
            model_name="event",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_gallery",
                to="events.eventgallery",
                verbose_name="Галерея",
            ),
            preserve_default=False,
        ),
    ]
