# Generated by Django 4.2.4 on 2024-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_gallery_event_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="gallery",
        ),
        migrations.AddField(
            model_name="event",
            name="gallery",
            field=models.ManyToManyField(
                blank=True,
                related_name="events_gallery",
                to="events.eventgallery",
                verbose_name="Галерея",
            ),
        ),
    ]
