# Generated by Django 4.2.4 on 2024-04-13 12:11

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_form_template_event_form_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='fields',
            field=models.JSONField(default=events.models.get_default_fields),
        ),
    ]
