# Generated by Django 4.2.4 on 2024-04-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_gallery_alter_event_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='eventformtemplate',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.formtemplate'),
        ),
    ]
