# Generated by Django 4.2.4 on 2024-04-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_formtemplate_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFormTemplate',
        ),
    ]
