# Generated by Django 4.2.4 on 2024-04-12 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_formtemplate_eventformtemplate_form_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformtemplate',
            name='fields',
            field=models.JSONField(default={'first_name': '', 'phone': ''}),
        ),
        migrations.AlterField(
            model_name='eventformtemplate',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.formtemplate'),
        ),
    ]
