# Generated by Django 4.2.4 on 2024-04-12 06:00

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventformtemplate_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformtemplate',
            name='fields',
            field=models.JSONField(default=events.models.get_default_fields),
        ),
    ]
