# Generated by Django 4.2.4 on 2024-04-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventformtemplate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_form_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_event', to='events.eventformtemplate'),
        ),
    ]
