# Generated by Django 4.2.4 on 2024-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_created_at_event_created_by_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offline',
            field=models.BooleanField(default=False, verbose_name='Офлайн'),
        ),
    ]
