# Generated by Django 4.2.4 on 2024-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialization_index'),
        ('events', '0008_event_record_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='users.specialization', verbose_name='Специализации на эвенте'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='specialization',
            field=models.CharField(max_length=200, verbose_name='Специализация'),
        ),
    ]
