# Generated by Django 4.2.4 on 2024-05-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_specializations_alter_speaker_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
