# Generated by Django 4.2.4 on 2024-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialization_index'),
        ('events', '0010_rename_data_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.specialization', verbose_name='Специализации на эвенте'),
        ),
    ]
