# Generated by Django 4.2.4 on 2024-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация'),
        ),
    ]
