# Generated by Django 4.2.4 on 2024-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_speaker_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='specialization',
            field=models.CharField(default=1, max_length=200, verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
