# Generated by Django 4.2.4 on 2024-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_speaker_foto_alter_speaker_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(null=True, upload_to='images/', verbose_name='Галерея')),
                ('caption', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery',
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='events_gallery', to='events.eventgallery', verbose_name='Галерея'),
        ),
    ]
