# Generated by Django 4.2.4 on 2024-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventgallery_remove_event_gallery_event_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='stream',
            field=models.URLField(blank=True, null=True),
        ),
    ]
