# Generated by Django 4.2.4 on 2024-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_is_archive_event_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='event',
            name='record_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на стрим'),
        ),
    ]
