# Generated by Django 4.2.4 on 2024-07-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_is_archive_alter_event_record_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='event_admin',
        ),
    ]
