# Generated by Django 4.2.4 on 2024-07-06 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_rename_created_by_event_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Администратор ивента'),
        ),
    ]
