# Generated by Django 4.2.4 on 2024-07-06 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_alter_event_event_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_admin',
        ),
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Администратор ивента'),
        ),
    ]
