# Generated by Django 4.2.4 on 2024-07-06 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0021_remove_event_event_admin_event_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_admins', to=settings.AUTH_USER_MODEL, verbose_name='Администратор ивента'),
        ),
    ]
