# Generated by Django 4.2.4 on 2024-07-11 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0022_alter_event_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_admin',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Администратор ивента'),
        ),
    ]
