# Generated by Django 4.2.4 on 2024-07-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_rejectionreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='rejection_reason',
            field=models.CharField(max_length=255, null=True, verbose_name='Причина отказа'),
        ),
    ]
