# Generated by Django 4.2.4 on 2024-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventformtemplate'),
        ('organaizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizator',
            name='speaker',
            field=models.ManyToManyField(to='events.speaker'),
        ),
    ]
