# Generated by Django 4.2.4 on 2024-04-10 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_eventformtemplate'),
        ('organaizer', '0002_organizator_speaker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizator',
            unique_together={('user', 'event')},
        ),
    ]
