# Generated by Django 4.2.4 on 2024-05-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organaizer', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizator',
        ),
    ]
