# Generated by Django 5.0.7 on 2024-08-01 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userevents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofilesnapshot',
            name='user_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userevents.userevent'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user_profile', 'event')},
        ),
    ]
