# Generated by Django 4.2.4 on 2024-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='application_status',
            field=models.CharField(choices=[('in_use', 'Не подана'), ('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='is_favorite', max_length=20),
        ),
    ]
