# Generated by Django 4.2.4 on 2024-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0005_alter_userevent_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='data_of_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время уведомления'),
        ),
    ]
