# Generated by Django 4.2.4 on 2024-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0006_userevent_data_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='application_status',
            field=models.CharField(choices=[('is_favorite', 'В избранном'), ('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='is_favorite', max_length=20),
        ),
    ]
