# Generated by Django 4.2.4 on 2024-07-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_event_admin'),
        ('users', '0009_remove_userprofile_stack_userprofile_stacks'),
        ('userevents', '0008_alter_userevent_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='events.event'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
