# Generated by Django 4.2.4 on 2024-07-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_stack_userprofile_stacks'),
        ('userevents', '0010_alter_userevent_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
