volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
        - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: hukumabob/backend
    env_file:
        - ../.env
    depends_on:
      - db
      - redis
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
  frontend:
    image: hukumabob/frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend  
  nginx:
    env_file:
        - ../.env  
    image: hukumabob/nginx
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/var/html/media/     
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
