export type TUserProfileValues = {
  id: number;
  first_name: string;
  last_name: string;
  user_photo: string;
  phone: string;
  place_of_work: string;
  position: string;
  online: boolean;
  offline: boolean;
  agreement_optional: boolean;
  date_of_birth: string;
  hobby: string;
  values: string;
  aims: string;
  cv: string;
  motivation: string;
  user: number;
  specialization: number;
  experience: number;
  familystatus: number;
  education: number;
  income: number;
  notification: number;
  country: number;
  city: number;
  [index: string]: any;
};

export type TFormDataPersonalValues = {
  first_name?: string;
  last_name?: string;
  date_of_birth?: string;
  familystatus?: number;
  country?: number;
  place_of_work?: string;
  position?: string;
  experience?: number;
  specialization?: number;
  income?: number;
  education?: number;
  hobby?: string;
  values?: string;
  aims?: string;
  cv?: string;
  motivation?: string;
  online?: boolean;
  offline?: boolean;
  user_photo?: string;
  notification?: number;
  [index: string]: any;
};

export type TProfileInitialState = {
  selectedTimeInterval: number;
  clickTimeInterval: boolean;
  smsChecked: boolean;
  emailChecked: boolean;
  approvalApplicationChecked: boolean;
  newEventsChecked: boolean;
};
