# Generated by Django 4.2.4 on 2024-04-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0003_education_familystatus_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familystatus',
            old_name='family_status',
            new_name='familystatus',
        ),
    ]
