# Generated by Django 4.2.4 on 2024-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0006_alter_city_country_id_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='minutes_before_notification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
