# Generated by Django 4.2.4 on 2024-04-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('place_of_work', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('agreement_required', models.BooleanField(default=True)),
                ('agreement_optional', models.BooleanField(default=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.experience')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
