# Generated by Django 4.2.4 on 2024-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="aims",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Жизненные цели"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cv",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Автобиография"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hobby",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Хобби"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="motivation",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Мотивации"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="place_of_work",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Место работы",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="values",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Жизненные ценности"
            ),
        ),
    ]
