# Generated by Django 4.2.4 on 2024-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_aims_userprofile_country_userprofile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
