# Generated by Django 4.2.4 on 2024-04-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='stack_id',
            new_name='specialization_id',
        ),
    ]
