# Generated by Django 4.2.4 on 2024-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_stack_id_stack_specialization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Index'),
            preserve_default=False,
        ),
    ]
