# Generated by Django 4.2.4 on 2024-04-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='family_status',
            new_name='familystatus',
        ),
    ]
