# Generated by Django 4.2.4 on 2024-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_family_status_userprofile_familystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agreement_required',
        ),
        migrations.AddField(
            model_name='user',
            name='agreement_required',
            field=models.BooleanField(default=True),
        ),
    ]
