# Generated by Django 4.2.4 on 2024-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offline',
            field=models.BooleanField(default=False, verbose_name='Offline'),
        ),
    ]
