# Generated by Django 4.2.4 on 2024-04-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0005_notification'),
        ('users', '0005_remove_userprofile_agreement_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.notification'),
        ),
    ]
