# Generated by Django 4.2.4 on 2024-06-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='specialization_id',
        ),
        migrations.AddField(
            model_name='stack',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.specialization', to_field='index', verbose_name='Specialization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='index',
            field=models.IntegerField(unique=True, verbose_name='Index'),
        ),
    ]
