# Generated by Django 4.2.4 on 2024-06-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0008_alter_notification_minutes_before_notification'),
        ('users', '0007_remove_stack_specialization_id_stack_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stack', verbose_name='Стек'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Стек'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialization', to_field='index', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreement_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное согласие'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='user_photo/', verbose_name='Фотография пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aims',
            field=models.TextField(blank=True, null=True, verbose_name='Жизненные цели'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.TextField(blank=True, null=True, verbose_name='Автобиография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.education', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.experience', verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='familystatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.familystatus', verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.income', verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Мотивации'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.notification', verbose_name='Уведомление'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='offline',
            field=models.BooleanField(default=False, verbose_name='Офлайн'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='values',
            field=models.TextField(blank=True, null=True, verbose_name='Жизненные ценности'),
        ),
    ]
