# Generated by Django 4.2.4 on 2024-04-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0005_notification'),
        ('users', '0008_alter_userprofile_experience_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.notification'),
        ),
    ]
