# Generated by Django 4.2.4 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_stack_alter_experience_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stack',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stacks',
            field=models.ManyToManyField(blank=True, to='users.stack', verbose_name='Стеки'),
        ),
    ]
