# Generated by Django 4.2.4 on 2024-04-08 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0006_alter_city_country_id_alter_city_name_and_more'),
        ('users', '0009_alter_userprofile_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreement_required',
            field=models.BooleanField(default=True, verbose_name='Agreement Required'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='user_photo/', verbose_name='User Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agreement_optional',
            field=models.BooleanField(default=False, verbose_name='Agreement Optional'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aims',
            field=models.TextField(blank=True, null=True, verbose_name='Aims'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.TextField(blank=True, null=True, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.education', verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='familystatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.familystatus', verbose_name='Family Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.income', verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.notification', verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, verbose_name='Place of Work'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.specialization', verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='values',
            field=models.TextField(blank=True, null=True, verbose_name='Values'),
        ),
    ]
